### ISSUE TITLE
Idee: PathUrl als Objekt, analog WebUrl

### ISSUE THREAD

**Issue by Obsthaendler** [Bettman66/ioBroker.frigate#38]
Hallo,

ich habe im Code gesehen, wie die WebUrl erzeugt wird. Konntest du bitte parallel einbauen, dass dazu auch eine PathUrl erzeugt wird. In der Config wird man einmal seinen absoluten Pfad eingeben, wie die WebUrl.
Das würde es vereinfachen auf eingebundene Volumes im iobroker zuzugreifen um Aktion mit Anhang zu senden.

z.B.
WebUrl: frigate.0.CAMNAME1.objects.person.web.snap.snap_0 = https://url.xyz//api/events/1690378666.347106-cz2nrb/snapshot.jpg
PathUrl: frigate.0.CAMNAME1.objects.person.path.snap.snap_0 = /var/lib/absoluterpath/clips/CAMNAME1-1690378666.347106-cz2nrb-clean.png

=> **%absoluterPath%** / clips / **%CAMNAME%** - **%EVENTID%** - clean.png

Weswegen ich diese Anfrage stelle ist, dass ich nur aus der EventId nicht den Pfad erzeugen kann, weil ich nicht den Camnamen ohne weiteres auslesen kann.

Dank und Gruß
Obsthaendler

**Comment by Bettman66** [comment]
Schau ich mir mal an.

**Comment by Bettman66** [comment]
Würde es genügen ein Objekt mit dem Inhalt 'CAMNAME1-1690378666.347106-cz2nrb' zu erzeugen ?
Quasi Kameraname + '-' + ID, da du ja den Pfad und die Endung selber hinzufügen kannst ?

**Comment by Bettman66** [comment]
Habe das Objekt CamID mal hinzugefügt.
Den Adapter über Github einfach aktualisieren.
